name: untitled
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

#----------- PACKAGES --------#
dependencies:
  flutter:
    sdk: flutter


  #----------- BACKEND PACKAGES --------#
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.1

  #----------- ICONS --------#
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8




  #----------- UTIL PACKAGES --------#
  http: ^1.3.0
  logger: ^2.5.0
  url_launcher: ^6.3.1
  intl: ^0.20.1
  flutter_native_splash: ^2.4.4
  lottie: ^3.3.1
  connectivity_plus: ^6.1.2
  smooth_page_indicator: ^1.2.0+3
  image_cropper: ^8.1.0
  image_picker: ^1.1.2

  #----------- STATE MANAGEMENT --------#
  get_storage: ^2.1.1
  get: ^4.6.6





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/IMG.jpg
  - assets/images/gcash.jpg
  - assets/images/seabank.jpg
  - assets/images/pinesville_logo.png
  - assets/images/ianimate.gif
  - assets/images/processdata.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_icons:
  image_path: "assets/images/pinesville_logo.png"
  android : true

